// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT7hIrVMZaL4aDu0DEf9mbtNumvLNotHc',
    appId: '1:998832064900:web:f8676a18e7ef33075ab5d1',
    messagingSenderId: '998832064900',
    projectId: 'ddcproject-f1c8c',
    authDomain: 'ddcproject-f1c8c.firebaseapp.com',
    storageBucket: 'ddcproject-f1c8c.appspot.com',
    measurementId: 'G-Z7715LZ0EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEWln0a0WDYnTR6cezaSr_neUOQ_QS8aQ',
    appId: '1:998832064900:android:7c08f886ab141b765ab5d1',
    messagingSenderId: '998832064900',
    projectId: 'ddcproject-f1c8c',
    storageBucket: 'ddcproject-f1c8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9IZZrq9PQysbxSY5ux11yHfOFJRKYdJ0',
    appId: '1:998832064900:ios:0c003099d6246be25ab5d1',
    messagingSenderId: '998832064900',
    projectId: 'ddcproject-f1c8c',
    storageBucket: 'ddcproject-f1c8c.appspot.com',
    androidClientId: '998832064900-688a1mnjqhvs1tpr30vdsjb2j391o5af.apps.googleusercontent.com',
    iosBundleId: 'com.example.diemdaochieuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9IZZrq9PQysbxSY5ux11yHfOFJRKYdJ0',
    appId: '1:998832064900:ios:0c003099d6246be25ab5d1',
    messagingSenderId: '998832064900',
    projectId: 'ddcproject-f1c8c',
    storageBucket: 'ddcproject-f1c8c.appspot.com',
    androidClientId: '998832064900-688a1mnjqhvs1tpr30vdsjb2j391o5af.apps.googleusercontent.com',
    iosBundleId: 'com.example.diemdaochieuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT7hIrVMZaL4aDu0DEf9mbtNumvLNotHc',
    appId: '1:998832064900:web:acd2735025b68b905ab5d1',
    messagingSenderId: '998832064900',
    projectId: 'ddcproject-f1c8c',
    authDomain: 'ddcproject-f1c8c.firebaseapp.com',
    storageBucket: 'ddcproject-f1c8c.appspot.com',
    measurementId: 'G-X2C5LTXBFP',
  );
}